version: '3.8'
services:
  callselly-to-foodtec:
    build: .
    container_name: callselly-to-foodtec
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env  
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm install && npm run dev"
