version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  callselly-to-foodtec:
    build: .
    container_name: callselly-to-foodtec
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env  
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

volumes:
  pgdata:
